name: Static patdiff Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.20
      options: --user root  # Run as root to avoid permission issues
    steps:
      - name: Install build dependencies
        run: apk add --no-cache build-base

      - name: Configure static build environment
        run: |
          sh <(curl -fsSL https://opam.ocaml.org/install.sh)
          opam init --bare --no-setup --bypass-checks --no-opamrc --disable-sandboxing
          opam switch create 5.3.0 --packages=ocaml-option-static,ocaml-option-musl
          eval $(opam env)

      - name: Install patdiff
        run: opam install patdiff --yes

      - name: Prepare artifacts directory
        run: mkdir -p artifacts

      - name: Extract binaries
        run: |
          BIN_DIR=$(opam var bin)
          cp $BIN_DIR/patdiff $BIN_DIR/patdiff-git-wrapper artifacts/

      - name: Generate checksums
        run: |
          cd artifacts
          sha256sum patdiff > patdiff.sha256
          sha256sum patdiff-git-wrapper > patdiff-git-wrapper.sha256

      - name: Package release artifacts
        run: |
          tar czvf "patdiff-static-$(date +%Y%m%d).tar.gz" artifacts/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patdiff-static-binaries
          path: patdiff-static-*.tar.gz
