name: Build static patdiff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install patchelf
        run: sudo apt-get install -y patchelf

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
      
      - name: Pip Install
        uses: BSFishy/pip-action@v1
        with:
          packages: staticx

      - name: OCaml/Opam cache
        id: opam-cache
        uses: actions/cache@v4
        with:
          path: "~/.opam"
          key: opam-cache

      - name: Set-up OCaml 5.3.0
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Install patdiff
        run: opam install patdiff

      - name: Prepare artifacts directory
        run: mkdir -p artifacts

      - name: Extract binaries
        run: |
          BIN_DIR=$(opam var bin)
          cp $BIN_DIR/patdiff-git-wrapper artifacts/
          staticx $BIN_DIR/patdiff artifacts/patdiff

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patdiff
          path: |
            artifacts/patdiff
            artifacts/patdiff-git-wrapper
